//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPMVCNomina.NominaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Control_Pago()
        {
            this.Nominas = new HashSet<Nomina>();
        }
    
        public int Id_Control_Pago { get; set; }
        public Nullable<int> Id_Parafiscal { get; set; }
        public Nullable<int> Id_Hora_Adicional { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nomina> Nominas { get; set; }
        public virtual Hora_Adicional Hora_Adicional { get; set; }
        public virtual Parafiscal Parafiscal { get; set; }
    }
}
