//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPMVCNomina.NominaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hora_Adicional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hora_Adicional()
        {
            this.Control_Pago = new HashSet<Control_Pago>();
        }
    
        public int IdHora_Adicional { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Valor_Hora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Control_Pago> Control_Pago { get; set; }
    }
}
