//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPMVCNomina.NominaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int Id_Nomina { get; set; }
        public Nullable<decimal> Valor_Apagar { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public string Mes { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> Id_Control_Pago { get; set; }
    
        public virtual Control_Pago Control_Pago { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
